# Docker compose for a full Magento 2 with Symfony connection
version: '2'

services:
  server-magento:
    build: ./.docker/nginx
    image: danneg/m2-nginx:1.15
    container_name: boxalino_m2_nginx
    volumes:
    - ./.docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - ./.docker/nginx/conf/sites-enabled:/usr/local/bin/nginx/sites-enabled
    - ./.docker/nginx/logs:/var/log/nginx
    volumes_from:
    - code-magento
    ports:
    - 80
    - 443
    links:
    - php
    - database-m2
    - redis
    - memcached
    - rabbitmq
    tty: true
    environment:
      SERVER_NAME: "dev-m2.danneg.com"
    env_file:
    - ./.docker/nginx/.env
    - ./.env

  php:
    build: ./.docker/php
    image: danneg/m2-php:7.0.20
    container_name: danneg_m2_php7.0.20
    volumes_from:
    - code-magento
    volumes:
    - ./.docker/php/conf/php.ini:/usr/local/etc/php/php.ini
    - ./.docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    - ./.docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
    - ./.docker/php/conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    - ./.docker/php/logs:/var/log/php
    ports:
    - 9000
    links:
    - code-magento
    - mailcatcher
    environment:
      PHP_IDE_CONFIG: "serverName=dev-m2.danneg.com"

  database-m2:
    build: ./.docker/mysql
    image: danneg/m2-mysql:5.7
    container_name: danneg_m2_mysql5.7
    volumes_from:
    - dbdata-m2
    links:
    - dbdata-m2
    volumes:
    - ./.docker/mysql/conf/:/etc/mysql/mysql.conf/
    - ./.docker/database/data:/var/lib/mysql
    ports:
    - 3306
    env_file:
    - ./.docker/mysql/.env

  redis:
    build: ./.docker/redis
    image: danneg/m2-redis:3.0.7
    container_name: danneg_m2_redis
    ports:
    - 6379

  memcached:
    build: ./.docker/memcached
    image: danneg/memcached:1.4.35
    container_name: danneg_m2_memcached
    ports:
    - 11211

  magento:
    build: ./.docker/cli
    image: danneg/m2-cli:7.0.20
    container_name: danneg_m2_cli
    links:
    - code-magento
    - rabbitmq
    - database-m2
    - redis
    - memcached
    volumes_from:
    - code-magento
    volumes:
    - ./.docker/cli/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
    - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa
    environment:
      PROJECT_ROOT: "/var/www/magento"
    env_file:
    - ./.docker/cli/.env
    - ./.docker/mysql/.env
    - ./.docker/rabbitmq/.env
    - ./.env

  rabbitmq:
    build: ./.docker/rabbitmq
    image: danneg/rabbitmq:3.6.9
    container_name: danneg_rabbitmq
    ports:
    - 5672
    - 15672
    - 4369
    env_file:
    - ./.docker/rabbitmq/.env

  mailcatcher:
    build: ./.docker/mailcatcher
    container_name: danneg_m2_mailcatcher
    image: danneg/m2-mailcatcher:0.6.4
    ports:
    - 1080:1080
    - 1025

  dbdata-m2:
    image: tianon/true
    container_name: danneg_m2_dbdata
    volumes:
    - /var/lib/mysql

  code-magento:
    build: ./.docker/volume
    image: danneg/m2-volume
    container_name: danneg_m2_volume
    volumes:
    - ./src/magento:/var/www/magento
    environment:
      SETUP_VOLUME: "/var/www/magento"
