# Docker compose for a full Magento 2 with Symfony connection
version: '2'

services:
  server-magento:
    build: ./.docker/nginx
    image: bmi/bxl-nginx:1.15
    container_name: bxl_m2_nginx
    volumes:
      - ./.docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/conf/sites-enabled:/usr/local/bin/nginx/sites-enabled
      - ./.docker/nginx/logs:/var/log/nginx
    volumes_from:
      - code-magento
    ports:
      - 80
      - 443
    links:
      - php
      - database
      - redis
      - memcached
      - rabbitmq
      - elasticsearch-magento
    tty: true
    environment:
      SERVER_NAME: "dev-m2.bxl.com"
    env_file:
      - ./.docker/nginx/.env
      - ./.env

  php:
    build: ./.docker/php
    image: bxl/m2-php:7.0.20
    container_name: bxl_m2_php7.0.20
    volumes_from:
      - code-magento
    volumes:
      - ./.docker/php/magento/conf/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./.docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./.docker/php/conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./.docker/php/logs:/var/log/php
    ports:
      - 9000
    links:
      - code-magento
      - mailcatcher
    environment:
        PHP_IDE_CONFIG: "serverName=dev-m2.bxl.com"

  database:
    build: ./.docker/mysql
    image: bxl/m2-mysql:5.7
    container_name: bxl_m2_mysql5.7
    volumes_from:
      - dbdata-magento
    volumes:
      - ./.docker/database/data:/var/lib/mysql
      - ./.docker/database/setup:/docker-entrypoint-initdb.d
    links:
      - dbdata-magento
    ports:
      - 3306
    env_file:
      - ./.docker/mysql/.env

  redis:
    build: ./.docker/redis
    image: bxl/m2-redis:3.0.7
    container_name: bxl_m2_redis
    ports:
      - 6379

  memcached:
    build: ./.docker/memcached
    image: bxl/memcached:1.4.35
    container_name: bxl_m2_memcached
    ports:
      - 11211

  magento:
    build: ./.docker/cli
    image: bxl/m2-cli:7.0.20
    container_name: bxl_m2_cli
    links:
      - code-magento
      - rabbitmq
      - database
      - redis
      - memcached
    volumes_from:
      - code-magento
    volumes:
      - ./.docker/cli/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa
    environment:
        PROJECT_ROOT: "/var/www/magento"
    env_file:
      - ./.docker/cli/.env
      - ./.docker/mysql/.env
      - ./.docker/rabbitmq/.env
      - ./.env

  elasticsearch-logs:
    build: ./.docker/elasticsearch/logserver
    image: bxl/logs-elasticsearch:5.4.0
    container_name: bxl_logs_elasticsearch
    volumes_from:
      - data-es
      - log-es
    volumes:
      - ./.docker/elasticsearch/logserver/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./.docker/elasticsearch/logserver/data:/var/data/elasticsearch/logserver
      - ./.docker/elasticsearch/logserver/logs:/var/logs/elasticsearch/logserver
    ports:
      - 9201:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    cap_add:
      - IPC_LOCK
    environment:
       ES_JAVA_OPTS: "-Xms750m -Xmx750m"

  elasticsearch-magento:
      build: ./.docker/elasticsearch/magento
      image: bxl/m2-elasticsearch:2.4.6
      container_name: bxl_m2_elasticsearch
      volumes_from:
        - data-es
        - log-es
      volumes:
        - ./.docker/elasticsearch/magento/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - ./.docker/elasticsearch/magento/data:/var/data/elasticsearch/magento
        - ./.docker/elasticsearch/magento/logs:/var/logs/elasticsearch/magento
      ports:
        - 9200:9200
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      mem_limit: 2g
      cap_add:
        - IPC_LOCK
      environment:
         ES_JAVA_OPTS: "-Xms750m -Xmx750m"

  rabbitmq:
    build: ./.docker/rabbitmq
    image: bxl/rabbitmq:3.6.9
    container_name: bxl_rabbitmq
    volumes:
      - ./.docker/rabbitmq/data/bxl_node:/var/lib/rabbitmq
    ports:
      - 5672
      - 15672
      - 4369
    env_file:
      - ./.docker/rabbitmq/.env

  phpmyadmin:
    build: ./.docker/phpmyadmin
    image: bxl/phpmyadmin:4.6
    container_name: bxl_m2_phpmyadmin
    volumes_from:
      - dbdata-magento
    ports:
      - 8080:80
    env_file:
      - ./.docker/phpmyadmin/.env

  mailcatcher:
     build: ./.docker/mailcatcher
     container_name: bxl_mailcatcher
     image: bxl/mailcatcher:0.6.4
     ports:
      - 1080:1080
      - 1025

  dbdata-magento:
    image: tianon/true
    container_name: bxl_m2_dbdata
    volumes:
      - /var/lib/mysql

  code-magento:
    build: ./.docker/volume
    image: bxl/m2-volume
    container_name: bxl_m2_volume
    volumes:
      - ./src/magento:/var/www/magento
    environment:
       SETUP_VOLUME: "/var/www/magento"

  data-es:
    image: tianon/true
    container_name: bxl_es_data
    volumes:
      - /var/data/elasticsearch

  log-es:
    image: tianon/true
    container_name: bxl_es_log
    volumes:
      - /var/logs/elasticsearch

  kibana:
    build: ./.docker/kibana
    image: bxl/kibana:5.5.2
    container_name: bxl_kibana
    links:
      - elasticsearch-logs
    volumes:
      - ./.docker/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601